# simple request
#GET http://localhost:8008/


POST http://localhost:8008/groups
Content-Type: application/json

{
  "hasPositions": true
}


POST http://localhost:8008/search
Content-Type: application/json

{
  "hasPositions": true
}


# debería dar error 
POST http://localhost:8008/search
Content-Type: application/json

{
  "hasFriends": true
}

POST http://localhost:8008/groups
Content-Type: application/json

{
  "hasPositions": true
}


